git clone https://github.com/yuraksisa/ysd_md_attachment.git
git clone https://github.com/yuraksisa/ysd_md_audit.git
git clone https://github.com/yuraksisa/ysd_md_booking.git
git clone https://github.com/yuraksisa/ysd_md_business_events.git
git clone https://github.com/yuraksisa/ysd_md_cms.git
git clone https://github.com/yuraksisa/ysd_md_comparison.git
git clone https://github.com/yuraksisa/ysd_md_configuration.git
git clone https://github.com/yuraksisa/ysd_md_entitymanagement.git
git clone https://github.com/yuraksisa/ysd_md_event.git
git clone https://github.com/yuraksisa/ysd_md_facebook.git
git clone https://github.com/yuraksisa/ysd_md_fieldset.git
git clone https://github.com/yuraksisa/ysd_md_integration.git
git clone https://github.com/yuraksisa/ysd_md_location.git
git clone https://github.com/yuraksisa/ysd_md_logger.git
git clone https://github.com/yuraksisa/ysd_md_mail.git
git clone https://github.com/yuraksisa/ysd_md_payment.git
git clone https://github.com/yuraksisa/ysd_md_media_gallery.git
git clone https://github.com/yuraksisa/ysd_md_price.git
git clone https://github.com/yuraksisa/ysd_md_profile.git
git clone https://github.com/yuraksisa/ysd_md_rac.git
git clone https://github.com/yuraksisa/ysd_md_search.git
git clone https://github.com/yuraksisa/ysd_md_social.git
git clone https://github.com/yuraksisa/ysd_md_system.git
git clone https://github.com/yuraksisa/ysd_md_translation.git
git clone https://github.com/yuraksisa/ysd_plugin_aspects.git
git clone https://github.com/yuraksisa/ysd_plugin_attachment.git
git clone https://github.com/yuraksisa/ysd_plugin_auth.git
git clone https://github.com/yuraksisa/ysd_plugin_background.git
git clone https://github.com/yuraksisa/ysd_plugin_booking.git
git clone https://github.com/yuraksisa/ysd_plugin_cms.git
git clone https://github.com/yuraksisa/ysd_plugin_community.git
git clone https://github.com/yuraksisa/ysd_plugin_configuration.git
git clone https://github.com/yuraksisa/ysd_plugin_contact.git
git clone https://github.com/yuraksisa/ysd_plugin_dashboard.git
git clone https://github.com/yuraksisa/ysd_plugin_delayed_jobs.git
git clone https://github.com/yuraksisa/ysd_plugin_education_employment.git
git clone https://github.com/yuraksisa/ysd_plugin_errors.git
git clone https://github.com/yuraksisa/ysd_plugin_event.git
git clone https://github.com/yuraksisa/ysd_plugin_facebook.git
git clone https://github.com/yuraksisa/ysd_plugin_forum.git
git clone https://github.com/yuraksisa/ysd_plugin_hobbies.git
git clone https://github.com/yuraksisa/ysd_plugin_integration.git
git clone https://github.com/yuraksisa/ysd_plugin_language.git
git clone https://github.com/yuraksisa/ysd_plugin_location.git
git clone https://github.com/yuraksisa/ysd_plugin_mail.git
git clone https://github.com/yuraksisa/ysd_plugin_media_gallery.git
git clone https://github.com/yuraksisa/ysd_plugin_payment.git
git clone https://github.com/yuraksisa/ysd_plugin_price.git
git clone https://github.com/yuraksisa/ysd_plugin_profile.git
git clone https://github.com/yuraksisa/ysd_plugin_rac.git
git clone https://github.com/yuraksisa/ysd_plugin_system.git
git clone https://github.com/yuraksisa/ysd_plugin_translation.git